In [1]:
print("CustomerIQ — Day 1")
print("Python is working!")

CustomerIQ — Day 1
Python is working!

In [5]:
import pandas as pd

df = pd.read_csv("../Data/Raw/online_retail_II.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (1067371, 8)

In [7]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Column names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

First 5 rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
print("DATA TYPES")
print(df.dtypes)

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

DATA TYPES
Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

MISSING VALUES
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

DUPLICATE ROWS
34335

In [9]:
# Convert InvoiceDate to datetime
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

# Basic dataset timeline
print("DATASET DATE RANGE")
print("Start date:", df["InvoiceDate"].min())
print("End date:", df["InvoiceDate"].max())

# Customer validation
print("\nUNIQUE CUSTOMERS")
print(df["Customer ID"].nunique())

# Invoice validation
print("\nUNIQUE INVOICES")
print(df["Invoice"].nunique())

# Missing Customer ID percentage
missing_customer_pct = df["Customer ID"].isnull().mean() * 100

print("\nMISSING CUSTOMER ID")
print(f"{missing_customer_pct:.2f}%")

DATASET DATE RANGE
Start date: 2009-12-01 07:45:00
End date: 2011-12-09 12:50:00

UNIQUE CUSTOMERS
5942

UNIQUE INVOICES
53628

MISSING CUSTOMER ID
22.77%

In [10]:
# Investigate duplicate rows

duplicate_rows = df[df.duplicated()]

print("Number of duplicate rows:")
print(duplicate_rows.shape[0])

display(duplicate_rows.head(10))

Number of duplicate rows:
34335

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [11]:
# Create a working copy
clean_df = df.copy()

# Remove exact duplicate rows
clean_df = clean_df.drop_duplicates()

# Remove rows without a Customer ID
clean_df = clean_df.dropna(subset=["Customer ID"])

# Convert InvoiceDate to datetime
clean_df["InvoiceDate"] = pd.to_datetime(clean_df["InvoiceDate"])

# Remove cancelled invoices
clean_df = clean_df[~clean_df["Invoice"].str.startswith("C")]

# Keep only positive quantities
clean_df = clean_df[clean_df["Quantity"] > 0]

# Keep only positive prices
clean_df = clean_df[clean_df["Price"] > 0]

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", clean_df.shape)

Original dataset shape: (1067371, 8)
Cleaned dataset shape: (779425, 8)

In [12]:
# Save cleaned dataset

clean_df.to_csv(
    "../Data/Processed/online_retail_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [13]:
# Create revenue column

clean_df["Revenue"] = clean_df["Quantity"] * clean_df["Price"]

print("Revenue column created!")
display(clean_df.head())

Revenue column created!

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [14]:
# Basic business metrics

total_revenue = clean_df["Revenue"].sum()

total_customers = clean_df["Customer ID"].nunique()

total_invoices = clean_df["Invoice"].nunique()

average_order_value = total_revenue / total_invoices

print("BUSINESS OVERVIEW")
print("----------------------")

print(f"Total Revenue: £{total_revenue:,.2f}")
print(f"Total Customers: {total_customers:,}")
print(f"Total Orders: {total_invoices:,}")
print(f"Average Order Value: £{average_order_value:,.2f}")

BUSINESS OVERVIEW
----------------------
Total Revenue: £17,374,804.27
Total Customers: 5,878
Total Orders: 36,969
Average Order Value: £469.98

In [15]:
# Calculate number of orders per customer

customer_orders = (
    clean_df
    .groupby("Customer ID")["Invoice"]
    .nunique()
)

repeat_customers = (customer_orders >= 2).sum()

one_time_customers = (customer_orders == 1).sum()

total_customers = clean_df["Customer ID"].nunique()

repeat_rate = repeat_customers / total_customers * 100

print("CUSTOMER BEHAVIOR")
print("----------------------")

print(f"Total Customers: {total_customers:,}")
print(f"Repeat Customers: {repeat_customers:,}")
print(f"One-Time Customers: {one_time_customers:,}")
print(f"Repeat Customer Rate: {repeat_rate:.2f}%")

CUSTOMER BEHAVIOR
----------------------
Total Customers: 5,878
Repeat Customers: 4,255
One-Time Customers: 1,623
Repeat Customer Rate: 72.39%

In [16]:
total_revenue / total_invoices

np.float64(469.98307414320107)